[2023-11-05T16:18:00.499+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_People_Places.load_places manual__2023-11-05T16:17:59.442714+00:00 [queued]>
[2023-11-05T16:18:00.516+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_People_Places.load_places manual__2023-11-05T16:17:59.442714+00:00 [queued]>
[2023-11-05T16:18:00.518+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-11-05T16:18:00.520+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-11-05T16:18:00.523+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-11-05T16:18:00.551+0000] {taskinstance.py:1309} INFO - Executing <Task(DockerOperator): load_places> on 2023-11-05 16:17:59.442714+00:00
[2023-11-05T16:18:00.559+0000] {standard_task_runner.py:55} INFO - Started process 626 to run task
[2023-11-05T16:18:00.566+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL_People_Places', 'load_places', 'manual__2023-11-05T16:17:59.442714+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL_people_places_dag.py', '--cfg-path', '/tmp/tmpeyzjshgx']
[2023-11-05T16:18:00.573+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask load_places
[2023-11-05T16:18:00.704+0000] {task_command.py:389} INFO - Running <TaskInstance: ETL_People_Places.load_places manual__2023-11-05T16:17:59.442714+00:00 [running]> on host 6e77a7a050e2
[2023-11-05T16:18:00.800+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_People_Places
AIRFLOW_CTX_TASK_ID=load_places
AIRFLOW_CTX_EXECUTION_DATE=2023-11-05T16:17:59.442714+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-05T16:17:59.442714+00:00
[2023-11-05T16:18:00.829+0000] {docker.py:306} INFO - Starting docker container from image load_places:latest
[2023-11-05T16:18:03.992+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=ETL_People_Places, task_id=load_places, execution_date=20231105T161759, start_date=20231105T161800, end_date=20231105T161803
[2023-11-05T16:18:04.054+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-11-05T16:18:04.107+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
